---
title: "역함수 정리와 음함수 정리"
number-sections: true
number-depth : 3
crossref:
  chapters: true
---

{{< include ../../latexmacros.qmd >}}

## 역함수 정리 {#sec-CM_inverse_function_theorem}

$C^1$ 급 함수 $f:\R\to \R$ 이 $f'(a)\ne 0$ 일 때 $(f^{-1})'(a) = 1/f'(a)$ 임을 안다. $f'(a)>0$ 일 경우 $a$ 의 어떤 근방에서 $f$ 는 전단사 함수이며 국소적으로 역함수가 존재하고 그 도함수도 구할 수 있다는 의미이다. 다변수 함수에서도 똑같이 성립한다. 

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_inverse_function_theorem_1}

$n$-입방체 $A\subset \R^n$ 에서 정의된 $F:A \to \R^n$ 이 $C^1$ 급이라고 하자. 어떤 양수 $M>0$ 이 존재하여 모든 $\bf{x}\in \text{int}(A)$ 에 대해 $|D_jf^i(\bf{x})|\le M$ 이면 다음이 성립한다.

$$
\bf{x},\,\bf{y}\in A \implies \|F(\bf{y})-F(\bf{x})\|\le n^2M \|\bf{y}-\bf{x}\|.
$$

:::

</div>

::: {.proof}

볼록집합에서의 중간값 정리(@cor-CM_mean_value_theorem_for_convex) 에 의해

$$
f^i(\bf{y})-f^i(\bf{x}) = \nabla f^i(\bf{c}_i) (\bf{y}-\bf{x})
$$

를 만족하는 $\bf{c}_i$ 가 $\bf{y}$ 와 $\bf{x}$ 를 잇는 직선상에 존재한다. 
$$
\begin{aligned}
\left| f^i(\bf{y})-f^i(\bf{x}) \right| &= \left| \sum_j D_j f^i (\bf{c}) (y^j-x^j)\right| \le nM\|\bf{y}-\bf{x}\|
\end{aligned}
$$

임을 안다. 이로부터

$$
\|F(\bf{y})-F(\bf{x})\| \le \sum_i \left|f^i(\bf{y})-f^i(\bf{x}) \right| \le n^2M\|\bf{y}-\bf{x}\|
$$

을 얻는다. $\square$


:::

</br> 이로부터 아래가 성립함을 안다.


<div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#prp-CM_inverse_function_theorem_1}
@lem-CM_inverse_function_theorem_1 의 조건에서 $F$ 는 $A$ 에서 고른 연속이다. 
:::
</div>

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_for_inverse_function_theorem_1}

$L\in \mathcal{L}(\R^n)$ 이 가역이며 $U\subset \R^n$ 이 열린 집합이고 $F:U \to \R^n$ 일 때 $F$ 가 $C^1$ 급 함수일 필요충분조건은 $L\circ F\in C^1$ 이다.

:::

</div>

::: {.solution}

선형사상 $L\in \mathcal{L}(\R^n)$ 은 $\R^n$ 전체 에서 연속이며 미분가능하다. 또한 $L'(\bf{x}) = L$ 이므로 $L$ 은 $C^1$ 함수이다. $(L\circ F)'(\bf{x}) = L\cdot F'(\bf{x})$ 이므로 $L \circ F$ 는 미분가능하며, $F$ 가 $C^1$ 함수이면 $L \circ F$ 도 $C^1$ 함수이다. $F = L^{-1}\circ (L \circ F)$ 이므로 $L\circ F$ 가 $C^1$ 함수이면 $F$ 역시 $C^1$ 함수이다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_for_inverse_function_theorem_2}

$L\in \mathcal{L}(\R^n)$ 이 가역이며 열린 집합 $U \subset \R^n$ 에서 정의된 미분가능한 함수 $F:U \to \R^n$ 에 대해 $G=L\circ F$ 라고 하자. 이 때 아래 ($a$), ($b$) 는 동치임을 보여라.

&emsp;($a$) $F:U\to \R^n$ 에 대해 미분가능한 역함수 $F^{-1}: F(U) \to U$ 가 존재한다.

&emsp;($b$) $G:U\to \R^n$ 에 대해 미분가능한 역함수 $G^{-1}: G(U) \to U$ 가 존재한다.
:::

</div>

::: {.solution}

($a \implies b$) $H=F^{-1}\circ L^{-1}$ 라고 하면 $F^{-1}$ 는 미분가능하므로 $H$ 도 미분가능하다. $H\circ G = I$ 이므로 $G^{-1}=H=F^{-1}\circ L^{-1}$ 이다.

($b\implies c$) $F=L^{-1}\circ G$ 이므로 위의 논리를 똑같이 적용 할 수 있다. 

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_inverse_function_theorem_2}

열린 집합 $A\subset \R^n$ 에 대해 $F: A\to \R^n$ 가 $C^1$ 함수 라고 하자. $\bf{a}\in A$ 이며 $\det(F'(\bf{a}))\ne 0$ 일 때 $\bf{a}$ 를 중심으로 하는 열린 $n$-입방체 $U\subset A$ 에 대해 아래의 부등식이 성립하는 $\alpha>0$ 가 존재한다.

$$
\bf{x},\, \bf{y}\in U \implies \|F(\bf{y}) - F(\bf{x})\| \ge \alpha \|\bf{y}-\bf{x}\|.
$$

:::

</div>

::: {.proof}

$L=F'(\bf{a})$ 이라고 하자. $\det (L)>0$ 이므로 $L$ 은 가역이다. $M_2=\|L^{-1}\|$ 이라고 하면 

$$
\|\bf{y}-\bf{x}\| = \left\|L^{-1}\cdot L(\bf{y} - \bf{x})\right\| \le M_2 \|L(\bf{y}-\bf{x})\|
$$

이므로 

$$
\|L(\bf{y}-\bf{x})\| \ge \dfrac{1}{M_2}\|\bf{y}-\bf{x}\|
$$

이다. 이제 $H(\bf{x}) := F(\bf{x})-L(\bf{x})$ 라고 하자. $H\in C^1$ 이며 $H'(\bf{x}) = F'(\bf{x})-L$, $H'(\bf{a})=\bf{0}$ 이다. $H'(\bf{x})$ 가 연속이므로 $\bf{a}$ 를 중심으로 하는 $n$-입방체 $U = C(\bf{a},\, \varepsilon)$ 가 존재하여 

$$
\bf{x}\in U \implies \|H'(\bf{x})\|\le \dfrac{1}{2nM_2}
$$ 

이다. $H(\bf{x}) = \begin{bmatrix} h^1(\bf{x})  & \cdots & h^n(\bf{x}) \end{bmatrix}^T$ 라고 할 때 중간값 정리(@thm-CM_mean_value_theorem_for_vector_function) 를 이용하면 $\bf{x}_1,\, \bf{x}_2\in U$ 일 때 어떤 $\bf{c}_i\in U$ 에 대해 

$$
|h^i(\bf{y})-h^i(\bf{x})| = |Dh^i(\bf{c}_i)\cdot (\bf{y}-\bf{x})|  \le \dfrac{1}{2nM_2}\|\bf{y}-\bf{x}\|
$$

이며, 따라서

$$
\begin{aligned}
\|H(\bf{y})-H(\bf{x})\| &\le \sum_{i=1}^n |h^i(\bf{y})-h^i(\bf{x})| \\[0.3em]
&\le n\cdot \dfrac{1}{2nM_2} \|\bf{y}-\bf{x}\| = \dfrac{1}{2M_2}\|\bf{y}-\bf{x}\|
\end{aligned}
$$

이다. 이로부터

$$
\begin{aligned}
\|\bf{y}-\bf{x}\| &\ge 2M_2 \|H(\bf{y})-H(\bf{x})\| \\[0.3em]
&= 2M_2 \|F(\bf{y}) - F(\bf{x}) - L(\bf{y}-\bf{x})\| \\[0.3em]
&\ge 2M_2 \|L(\bf{y} - \bf{x})\| - 2M_2\|F(\bf{y})-F(\bf{x})\| \\[0.3em]
& \ge 2\|\bf{y} - \bf{x}\| - 2M_2 \|F(\bf{y})-F(\bf{x})\|
\end{aligned}
$$

이며 따라서

$$
\|F(\bf{y})-F(\bf{x})\| \ge \dfrac{1}{2M_2}\|\bf{y}-\bf{x}\|
$$

이다. $\square$

:::

</br>

@lem-CM_inverse_function_theorem_2 은 $\det(F'(\bf{a}))\ne 0$ 이면 $\bf{a}$ 를 중심으로 하는 어떤 열린 입방체 에서 $F$ 가 단사가 됨을 의미한다. $\bf{x}_1\ne \bf{x}_2$ 이면 $\|F(\bf{x}_1)-F(\bf{x}_2)\|>0$ 이 기 때문이다. 이제 위의 보조정리에서 계속 진행해보자.

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_inverse_function_theorem_3}

열린 집합 $A\subset \R^n$ 에 대해 $F:A \to \R^n$ 이 $C^1$-급 함수 이며 $\det(F'(\bf{a}))\ne 0$ 라고 하자. 그렇다면 $\bf{a}$ 를 포함하는 열린 집합 $V$ 와 $F(\bf{a})$ 를 포함하는 열린 집합 $W$ 가 존재하여 $F:V\to W$ 에 대한 역함수 $F^{-1}: W \to V$ 가 존재한다.

:::

</div>

::: {.proof}
$F$ 는 아래의 명제 ($C-1$), ($C-2$), ($C-3$) 를 모두 만족한다.

($C-1$) @lem-CM_inverse_function_theorem_2 로 부터 $\bf{a}$ 를 중심으로 하는 열린 $n$-입방체 $U_1\subset A$ 이 존재하여 어떤 $\alpha>0$ 에 대해 

$$
\bf{x}_1,\,\bf{x}_2\in U_1 \implies \|F(\bf{x}_1)-F(\bf{x}_2)\| \ge \alpha\|\bf{x}_1-\bf{x}_2\|
$$

임을 안다. 즉 $U_1$ 에서 $F$ 는 단사이다.

($C-2$) $\det$ 함수와 $F'$ 이 모두 연속이므로 $\bf{a}$ 를 중심으로 하는 어떤 열린 $n$-입방체 $U_2\subset A$ 에 대해 $\bf{x}\in U_2 \implies \det(F'(\bf{x})) \ne 0$ 이다. 

($C-3$) $D_jf_i$ 가 연속이므로 $\bf{a}$ 를 포함하는 어떤 열린 $n$-입방체 $U_3\subset A$ 에서 

$$
\bf{x}\in U_3 \implies \|D_jf_i(\bf{x})-D_jf_i(\bf{a})\|< \dfrac{1}{2n^2}
$$

이며, 따라서 $U_3$ 에서 $D_jf_i(\bf{x})$ 는 유계이다. (@lem-CM_inverse_function_theorem_1 의 조건)

이제 $\bf{a}$ 를 중심으로 $U_1 \cap U_2 \cap U_3$ 에 포함되는 열린 $n$-입방체 $U$ 를 생각하자. $U$ 를 작게 잡아 $\partial U \cap \partial U_1 = \varnothing$ 이 되도록 잡을 수 있다. 이 때 $\partial U$ 는 $U$ 의 경계점([@KKK2011 연습문제 2.7.6](https://julia-kaeri.github.io/MathematicalAnalysis/src/part2/2_1_basic_topology.html#exr-MA_KKK_2_7_6)) 이다.

($a$) $\partial U$ 는 유계인 닫힌 집합이므로 옹골집합이며 $\bf{a}$ 를 포함하지 않는다. $\partial U \subset U_1$ 이며 $U_1$ 에서 $F$ 는 단사이므로 $F(\bf{a}) \notin F(\partial U)$ 이다. 

($b$) $F$ 가 연속이므로 $F(\partial U)$ 도 옹골집합이며 따라서 모든 $\bf{x}\in \partial U$ 에 대해 $\|F(\bf{x})-F(\bf{a})\| \ge d$ 인 $d>0$ 이 존재한다. 

이 $d$ 에 대해 집합 $W$ 를 다음과 같이 정의한다.

$$
W:= \{\bf{y} \in \R^n: \|\bf{y}-F(\bf{a})\|<d/2\}.
$$

이 때 $W$ 는 열린집합이다([@Rudin1976 연습문제 4.3](https://julia-kaeri.github.io/MathematicalAnalysis/src/part2/2_3_continuity_of_functions.html#exr-MA_rudin_4_3)). 그렇다면 $\bf{y}\in W,\, \bf{x}\in \partial U$ 일 때

$$
\begin{aligned}
\|\bf{y}-F(\bf{x})\| &= \|F(\bf{x})-F(\bf{a})-\bf{y}+F(\bf{a})\| \\[0.3em]
 &\ge \|F(\bf{x})-F(\bf{a})\| - \|\bf{y}-F(\bf{a})\|  > \dfrac{d}{2} > \|\bf{y}-F(\bf{a})\|
\end{aligned} 
$$

이다. 

($C-4$) 즉 $\bf{y}\in W,\, \bf{x}\in \partial U$ 일 때

$$
\|\bf{y}-F(\bf{x})\|> \|\bf{y}-F(\bf{a})\|
$$

이다. 

이제 $\bf{y}\in W$ 에 대해 $\bf{y}=F(\bf{x})$ 를 만족하는 $\bf{x}\in U$ 는 항상 유일하게 존재함을 보이자. 이를 위해 $\overline{U} = U \cup \partial U$ 에서 정의된 $g:\overline{U} \to \R$ 을 다음과 같이 정의한다.

$$
g(\bf{x}) := \|\bf{y}-F(\bf{x})\|^2
$$

이 함수는 연속이며 $\overline{U}$ 는 옹골집합이므로 최소값을 가진다. $\bf{x} \in \partial U$ 라면 ($C-4$) 에 의해 최소값이 될 수 없으므로 $g$ 를 최소로 하는 $\bf{x}$ 는 $\bf{x}\in U$ 이며 따라서 $g'(\bf{x})=0$ 이므로

$$
\bf{0}=g'(\bf{x}) = 2 F'(\bf{x})\bf{\cdot} (\bf{y}-F(\bf{x}))
$$

이다. 그런데 $\det(F'(\bf{x})) \ne 0$ 이므로(($C-2$) 조건) $\bf{y}=F(\bf{x})$ 이어야 한다. 즉 $\bf{y}=F(\bf{x})$ 인 $\bf{x}\in U$ 가 존재한다. $U\subset U_0$ 이므로 ($C-1$) 에 의해 $U$ 에서 유일하다. 

$V=U\cap F^{-1}(W)$ 는 열린 집합이며 $F:V\to W$ 는 전단사이다. 즉 $F^{-1}:W \to V$ 가 존재한다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_inverse_function_theorem}

#### 역함수 정리

열린 집합 $A\subset \R^n$ 에 대해 $F:A \to \R^n$ 이 $C^1$-급 함수 이며 $\det(F'(\bf{a}))\ne 0$ 라고 하자. $\bf{a}$ 를 포함하는 열린 집합 $V$ 와 $F(\bf{a})$ 를 포함하는 열린 집합 $W$ 가 존재하여 $F:V\to W$ 에 대한 미분가능한 $F^{-1}: W \to V$ 가 존재한다. $F^{-1}$ 은 $W$ 에서 미분가능하며 모든 $\bf{y}\in W$ 에 대해

$$
(F^{-1})'(\bf{y}) = \left[F'(F^{-1}(\bf{y}))\right]^{-1}.
$$ {#eq-thm-CM_inverse_function_theorem_1}

이다.
:::

</div>

::: {.proof}

@lem-CM_inverse_function_theorem_3 에서 보인 부분을 제외하면 $F^{-1}$ 이 $W$ 에서 미분가능하며 $(F')^{-1}$ 이 @eq-thm-CM_inverse_function_theorem_1 이라는 것을 보이면 된다. 우선 $F^{-1}$ 이 연속임을 보이자. $\bf{y}_1,\,\bf{y}_2 \in W$ 일 때 @lem-CM_inverse_function_theorem_3 증명의 ($C-1$) 조건으로부터

$$
\|F^{-1}(\bf{y}_1)-F^{-1}(\bf{y}_2)\|  \le  \dfrac{1}{\alpha} \|\bf{y}_1-\bf{y}_2\|
$${#eq-thm-CM_inverse_function_theorem_2}

이다. 따라서 $F^{-1}$ 은 $W$ 에서 연속이다.

$L= F'(\bf{x})$ 라고 하자. @thm-CM_chain_rule 증명 방법을 사용한다. $\bf{x}_1\in V$ 에 대해

$$
F(\bf{x}_1) = F(\bf{x}) + L(\bf{x}_1-\bf{x}) + P(\bf{x}_1-\bf{x})
$$

라고 하면

$$
\lim_{\bf{x}_1\to \bf{x}} \dfrac{\|P(\bf{x}_1-\bf{x})\|}{\|\bf{x}_1-\bf{x}\|} = 0
$$ {#eq-thm-CM_inverse_function_theorem_3}

이다. 따라서

$$
L^{-1}(F(\bf{x}_1)-F(\bf{x})) = \bf{x}_1 - \bf{x} + L^{-1}(P(\bf{x}_1-\bf{x}))
$$

이다. 각각의 $\bf{y}_1\in W$ 에 대해 $\bf{y}_1 = F(\bf{x}_1)$ 인 $\bf{x}_1\in V$ 가 유일하게 존재하므로

$$
F^{-1}(\bf{y}_1) = F^{-1}(\bf{y}) + L^{-1}(\bf{y}_1-\bf{y}) - L^{-1}(P(F^{-1}(\bf{y}_1) - F^{-1}(\bf{y})))
$$

이다. 즉 

$$
\lim_{\bf{y}'\to \bf{y}} \dfrac{\left\| L^{-1}(P(F^{-1}(\bf{y}') - F^{-1}(\bf{y})))\right\|}{\|\bf{y}'-\bf{y}\|} = 0
$$

임을 보이면 된다. $L^{-1}$ 이 선형변환이므로 @exr-CM_spivak_1_10 에 따라

$$
\lim_{\bf{y}_1\to \bf{y}} \dfrac{\left\| P(F^{-1}(\bf{y}_1) - F^{-1}(\bf{y}))\right\|}{\|\bf{y}_1-\bf{y}\|} = 0
$$ {#eq-thm-CM_inverse_function_theorem_4}

만 보이면 된다. 

$$
\dfrac{\left\| P(F^{-1}(\bf{y}_1) - F^{-1}(\bf{y}))\right\|}{\|\bf{y}_1-\bf{y}\|} = \dfrac{\left\| P(F^{-1}(\bf{y}_1) - F^{-1}(\bf{y}))\right\|}{\|F^{-1}(\bf{y}_1)-F^{-1}(\bf{y})\|}  \dfrac{{\|F^{-1}(\bf{y}_1)-F^{-1}(\bf{y})\|}}{\|\bf{y}_1-\bf{y}\|}
$$

인데. $F^{-1}$ 이 연속이므로 @eq-thm-CM_inverse_function_theorem_3 에 따라 첫번째 항의 $\bf{y}_1\to \bf{y}$ 극한은 $0$ 이다. 또한 @eq-thm-CM_inverse_function_theorem_2 에 따라 두번째 항은 $1/\alpha$ 보다 작으므로 @eq-thm-CM_inverse_function_theorem_4 가 성립한다. 

즉 $\bf{y}=F(\bf{x})$ 일 때 

$$
(F^{-1})'(\bf{y}) = (F'(\bf{x}))^{-1} = [F'(F^{-1}(\bf{y}))]^{-1}
$$

이다. $\square$

:::

</br>

어떤 열린 $U,\,V\subset \R^n$ 에서 정의된 $C^1$ 급 함수가 역시 $C^{1}$ 함수인 역함수를 가질 때 이 함수를 미분동형사상이라고 한다. 미분동형사상에 대해서는 이후 좀 더 자세히 다루기로 한다.

</br>

### 연습문제 {.unnumbered}

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_36}
#### Spivak 2.36

$A\subset \R^n$ 이 열린 집합이며 $F:A \to \R^n$ 이 $C^1$ 급 함수이고 모든 $\bf{x}\in A$ 에 대해 $\det (F'(\bf{x}))\ne 0$ 이다. $F(A)$ 는 열린 집합이며 $F^{-1}:F(A)\to A$ 는 미분가능함을 보여라. $B\subset A$ 가 열린 집합이면 $F(B)$ 도 열린 집합임을 보여라.
:::

</div>

::: {.solution}

[연속함수와 역사상의 성질](https://julia-kaeri.github.io/MathematicalAnalysis/src/part2/2_3_continuity_of_functions.html#sec-MA_continuity_and_inverse_image) 로부터 $F:\R^n \to \R^n$ 에서 $F$ 가 연속가 연속인 것과 임의의 열린 집합 $W\subset \R^n$ 에 대해 $F^{-1}(W)$ 가 열린 집합인 것은 동치이다. 

역함수 정리에 의해 $\bf{x}\in A$ 에 대해 $\bf{x}$ 를 포함하는 열린 집합 $V_x \subset A$ 와 $F(\bf{x})$ 를 포함하는 열린 집합 $W_x$ 가 존재하여 $F^{-1} : W_x \to V_x$ 는 미분 가능 함수이므로 연속이다. $\bf{y}_1\in F(A)$ 이면 어떤 $\bf{x}_1$ 에 대해 $F(\bf{x}_1)=\bf{y}_1$ 이며 따라서 $\bf{x}_1$ 을 포함하는 어떤 열린집합 $V_1$ 과 $\bf{y}_1$ 을 포함하는 어떤 열린집합 $W_1$ 에 대해 미분가능한, 따라서 연속인 $F^{-1}: W_1 \to V_1$ 이 존재한다. $\bf{y}\in F(V_1) = (F^{-1})^{-1}(V_1) \subset F(A)$ 는 열린 집합이므로 $F(A)$ 는 열린집합이다. $F(A) = \bigcup_{\bf{x}\in A} W_x$ 이므로 $F^{-1}:F(A) \to A$ 는 미분가능이다. 또한 $B\subset A$ 가 열린 집합이면 당연히 $F(B)$ 도 열린 집합임은 자명하다.

:::


</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_37}
#### Spivak 2.37

($a$) $f:\R^2 \to \R$ 이 $C^1$ 급 함수이다. $f$ 가 단사함수가 될 수 없음을 보여라.

($b$) ($a$) 의 결과를 $m<n$ 일 때의 $F:\R^n \to \R^m$ 으로 일반화하라.

:::

</div>

::: {.solution}

아래 명제를 사용한다. 증명은 쉽다. $(\bf{a},\,\bf{b})$ 를 중심으로 하는 $U$ 에 포함되는 열린 $n$-입방체를 생각하라.

>(**P1**) $\R^{m+p}$ 에서의 열린 집합 $U$ 에 대해 $\bf{a}\in \R^m,\, \bf{b}\in \R^p$, $(\bf{a},\,\bf{b})\in U$ 일 때 어떤 $\tilde{\bf{b}}\in \R^p$ 이 존재하여 $(\bf{a},\,\tilde{\bf{b}})\in U$ 이다.


($a$) @exr-CM_spivak_2_22 에 따라 모든 $(x,\,y) \in \R^2$ 에서 $D_1f = D_2f=0$ 이면 $f$ 는 상수함수이므로 단사가 아니다. 이제 어떤 $(a,\,b)\in \R^2$ 에서 $D_1f(a,\,b) \ne 0$, $D_2 f(a,\,b) = 0$ 인 경우를 생각하자.
$C^1$ 함수이므로 $(a,\,b)$ 을 포함하는 어떤 열린 집합 $A$ 에서 $(x,\,y)\in A \implies D_1f(x,\,y)\ne 0$ 이다. $G:A \to \R^2$ 를 $G(x,\,y) := (f(x,\,y),\, y)$ 라고 하자. 

$$
\det (G'(a,\,b)) = \det \left(\begin{bmatrix} D_1f(a,\,b) & D_2f(a,\,b) \\ 0 & 1 \end{bmatrix}\right) = D_1f(a,\,b) \ne 0
$$  

이며 @exr-CM_spivak_2_36 에 의해 $G(A)$ 는 열린집합이다. $G(a,\,b)=$$(f(a,\,b),\, b)$$\in G(A)$ 이므로 어떤 $\widetilde{b} \ne b$ 에 대해 $(f(a,\,b),\,\widetilde{b}) \in G(A)$ 이다(**P1**). 그런데 $f$ 가 단사이므로 $f(a,\,\widetilde{b}) \ne f(a,\,b)$ 이다. 따라서 $(f(a,\,b),\,\widetilde{b}) \notin G(A)$ 이어야 하므로 모순. 따라서 $f$ 는 단사 일 수 없다.

어떤 $(a,\,b)\in A$ 에 대해 $D_1f(a,\,b)= 0$ 이라고 하자. $(x,\,y) \in U$ 에 대해 $D_2f(x,\,y) \ne 0$ 일 때 $H(x,\,y) =(x,\, D_2f(x,\,y))$ 라고 하면

$$
\det (H'(a,\,b)) = \det \left(\begin{bmatrix} 1 & 0 \\ D_1f(a,\,b) & D_2f(a,\,b)\end{bmatrix} \right)= D_2f(a,\,b)
$$

이다. 결국 $D_1f(x,\,y) \ne 0$ 일 때와 변수 순서만 바뀐 경우이므로 $f$ 는 단사 일 수 없다.

($b$) $F: \R^{m+l} \to \R^m$ 이라고 하자. $\bf{x}\in\R^m,\, \bf{y}\in \R^l$ 에 대해 $G(\bf{x},\,\bf{y}) = (F(\bf{x},\,\bf{y}),\,\bf{y})$ 라고 하자. 모든 $(\bf{x},\,\bf{y})\in \R^{m+l}$ 에 대해 $F'(\bf{x},\,\bf{y})= \bf{0}$ 이라면 $F$ 는 상수함수이므로 단사가 아니다.

이제 $\det\left(\dfrac{\partial F}{\partial \bf{x}}(\bf{a},\,\bf{b})\right) \ne \bf{0}$ 이라고 하자. $G'(\bf{a},\bf{b}) = \begin{bmatrix} \dfrac{\partial F}{\partial \bf{x}}(\bf{a},\bf{b}) & \dfrac{\partial F}{\partial \bf{y}}(\bf{a},\bf{b}) \\ 0 & I_l\end{bmatrix}$

이므로 $\det (G'(\bf{a},\bf{b})) = \det \left(\dfrac{\partial F}{\partial\bf{x}}(\bf{a},\bf{b})\right)$ 이다. 따라서 어떤 열린 집합 $U,\,W\subset \R^{m+l},\, (\bf{a},\,\bf{b})\in U$ 이 존재하여 $G:U\to W$ 는 미분가능한 역함수를 갖는다. $G(\bf{a},\bf{b})\in W$ 이고 $W$ 가 열린 집합이므로 어떤 $\overline{\bf{b}}\ne \bf{b}$ 에 대해 $(F(\bf{a},\bf{b}),\overline{\bf{b}})\in W$ 이다. 그런데 $F$ 는 단사이므로 $(F(\bf{a},\bf{b}),\overline{\bf{b}})\notin W$ 이어야 하므로 모순. 따라서 $F$ 는 단사 일 수 없다. $\det\left(\dfrac{\partial F}{\partial \bf{y}}(\bf{a},\bf{b})\right)\ne 0$ 일 때에도 같은 방법으로 보일 수있다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_38}
#### Spivak 2.38

($a$) $f:\R \to \R$ 이 모든 $x\in \R$ 에 대해 $f'(x) \ne 0$ 이면 $f$ 는 단사임을 보여라.

($b$) $F:\R^2 \to \R^2$ 가 $F(x,\,y) := \begin{bmatrix} e^x \cos y & e^x \sin y\end{bmatrix}^T$ 이다. $F'(x,\,y) \ne 0$ 이지만 $F$ 는 단사가 아님을 보여라.

:::

</div>

::: {.solution}

($a$) $a<b$ 에 대해 $f(b)-f(a) = (b-a)f'(c)$ 를 만족하는 $c\in (a,\,b)$ 가 존재해야 한다. $f(a)=f(b)$ 이면 $f'(c) = 0$ 이어야 하는데 가정에 모순. 

($b$) $F'(x,\,y) = \begin{bmatrix} e^x \cos y & - e^x \sin y \\ e^x \sin y & e^x \cos y\end{bmatrix}$ 이므로 $\det(F'(x,\,y)) =e^x \ne 0$ 이지만 $F(x,\,y) = F(x,\, 2\pi + y)$ 이므로 단사가 아니다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_39}
#### Spivak 2.39
$f:\R \to \R$ 이 다음과 같이 정의되었다.

$$
f(x) = \left\{\begin{array}{ll} \dfrac{x}{2} + x^2 \sin \dfrac{1}{x}, \qquad & x\ne 0,\\ 0 & x = 0\end{array}\right.
$$

도함수가 연속이 아님을 보여라.

:::

</div>

::: {.solution}

$$
f'(x)  = \dfrac{1}{2} + 2x \sin \dfrac{1}{x} - \cos \dfrac{1}{x}
$$

이며 $\lim_{x\ to 0}$ 은 존재하지 않는다. 그러나

$$
f'(0) = \lim_{t \to 0}\left(\dfrac{1}{2} + t \sin \dfrac{1}{t}\right) = \dfrac{1}{2}
$$

이므로 도함수는 연속이지 않다. 

:::

</br>

## 음함수 정리 {#sec-CM_implicit_function_theorem}

$\bf{x}\in \R^n,\, \bf{y}\in \R^m$ 에 대해 $(\bf{x},\, \bf{y}) := (x_1,\ldots,\,x_n,\, y_1,\ldots,\,y_m)$ 라고 하자. $L\in \mathcal{L}(\R^{n}\times \R^m,\, \R^m)$ 일 때 $L$ 를 $L_x\bf{x}=L(\bf{x},\,\bf{0}),\, L_y \bf{y} = L(\bf{0},\, \bf{y})$ 인 두 선형변환 $L_x,\,L_y$ 로 분리할 수 있다. 그렇다면

$$
L(\bf{x},\,\bf{y}) = L_x\bf{x} + L_y\bf{y}
$${#eq-CM_split_of_linear_operator}

이다. 이 때 $L$ 의 행렬 형태는 $\begin{bmatrix} L_x & L_y \end{bmatrix}$ 임은 쉽게 알 수 있다.


</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#lem-CM_implicit_function_theorem_rudin}

$L\in \mathcal{L}(\R^{n}\times \R^m,\, \R^m)$ 에서 $L_y$ 가 가역행렬이라고 하자. 각각의 $\bf{h}\in \R^n$ 에 대해 $L(\bf{h},\,\bf{k})=\bf{0}$ 이 되도록 하는 $\bf{k}\in \R^m$ 이 유일하게 존재하며 그 $\bf{k}$ 는 다음과 같다.

$$
\bf{k} = -(L_y)^{-1} L_x\bf{h}.
$$ {#eq-CM_split_of_linear_operator_2}


::: 

</div>

::: {.proof}
$L_y$ 가 가역행렬이므로 유일하다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_implicit_function_theorem}

#### 음함수 정리

열린 $E\subset \R^{n}\times \R^m$ 에서 정의된 $F:E \to \R^m$ 이 $C^1$ 함수이고 어떤 $(\bf{a},\,\bf{b}) \in E$ 에서 $F(\bf{a},\bf{b})=\bf{0}$ 이라고 하자. $L=F'(\bf{a},\,\bf{b})$ 이라고 할 때 $L=\begin{bmatrix} L_x &L_y\end{bmatrix}$ 라고 하자. 여기서 $L_y$ 는 $m \times m$ 행렬이다. $L_y$ 가 가역이면 어떤 $(\bf{a},\,\bf{b})$ 를 포함하는 열린집합 $U$ 와 $\bf{a}$ 를 포함하는 열린 집합 $W\subset \R^n$ 가 존재하여

&emsp;($a$) 각각의 $\bf{x}\in W$ 에 대해 유일한 $\bf{y}\in \R^m$ 이 존재하여 $(\bf{x},\,\bf{y})\in U,\,F(\bf{x},\,\bf{y})=\bf{0}$ 이고,

&emsp;($b$) ($a$) 에 의해 $\bf{x}=G(\bf{y})$ 라 놓을 수 있는데, $G$ 는 $C^1$ 급 함수이며 $G(\bf{a})=\bf{b}$ 이다.

&emsp;($c$) $G'(\bf{a}) = -(L_y)^{-1}L_x$ 이다.

::: 

</div>

::: {.proof}

($a$) $H:E \to \R^{n}\times \R^{m}$ 을 아래와 같이 정의한다.

$$
H(\bf{x},\,\bf{y}) := (\bf{x},\,F(\bf{x},\,\bf{y})).
$$ {#eq-thm-CM_implicit_function_theorem_1}

그렇다면 $H$ 는 $C^1$ 급 함수임은 자명하며

$$
H'(\bf{x},\,\bf{y}) = \begin{bmatrix} I_n & 0 \\ D_\bf{x} F(\bf{x},\,\bf{y}) & D_\bf{y} F(\bf{x},\,\bf{y})\end{bmatrix},\quad H'(\bf{a},\,\bf{b}) = \begin{bmatrix}  I_n & 0 \\ L_x & L_y \end{bmatrix}
$${#eq-thm-CM_implicit_function_theorem_2}

이다. $L_y$ 가 가역이므로 $\det (H'(\bf{a},\bf{b})) = \det (L_x) \ne 0$ 이고 따라서 $H'(\bf{a},\,\bf{b})$ 는 가역이다. 


$H'(\bf{a},\,\bf{b})$ 가 가역이므로 역함수 정리에 의해 $(\bf{a},\,\bf{b})$ 를 포함하는 어떤 열린 집합 $U$ 와 $(\bf{a},\,\bf{0})$ 를 포함하는 어떤 열린 집합 $V$ 가 존재하여 $H:U\to V$ 는 전단사함수이고, 그 역함수 $H^{-1}:V\to U$ 는 $C^1$ 급 함수이다. 


$W:=\{\bf{x}\in \R^n: (\bf{x},\,\bf{0}) \in V\}$ 라고 하자. $\bf{a}\in W$ 이며 $V$ 가 열린 집합이므로 $W$ 도 열린 집합이다(@exr-CM_for_implicit_theorem_1). $\bf{x}\in W$ 이면 $H(\bf{x},\bf{y})=(\bf{x},\bf{0})$ 인 $(\bf{x},\,\bf{y})\in U$ 가 존재하며 @eq-thm-CM_implicit_function_theorem_1 에 따라 $F(\bf{x},\bf{y})=\bf{0}$ 이다. $\overline{\bf{y}} \ne \bf{y}$ 에 대해 $(\bf{x},\overline{\bf{y}})\in U$ 이고 $F(\bf{x},\overline{\bf{y}})=\bf{0}$ 이라면

$$
H(\bf{x},\overline{\bf{y}}) = H(\bf{x},\bf{y})
$${#eq-thm-CM_implicit_function_theorem_3}

이다. $H$ 는 $U$ 에서 전단사 이므로 $\overline{\bf{y}}=\bf{y}$ 이다. 

($b$) 각각의 $\bf{x}\in W$ 에 대해 $F(\bf{x},\,\bf{y}) = \bf{0}$ 인 $\bf{y}$ 가 유일하게 정해지므로 이를 함수 $G(\bf{x})=\bf{y}$ 로 놓자. 즉 $\bf{x}\in W$ 에 대해 $H(\bf{x},G(\bf{x}))=(\bf{x},\,\bf{0})$ 이며 

$$
(\bf{x},\,G(\bf{x})) = H^{-1}(\bf{x},\, \bf{0})
$${#eq-thm-CM_implicit_function_theorem_4}

이다. $H^{-1}$ 이 $C^1$ 급 함수이므로 $G$ 역시 $C^1$ 급 함수이다. $\bf{a}\in W$ 이므로 $G(\bf{a})=\bf{b}$ 이다. 

($c$) @eq-thm-CM_implicit_function_theorem_2 의 두번째 식과 $H(\bf{x},\,G(\bf{x}))= (\bf{x},\,0)$ 에 대한 연쇄법칙을 이용하면

$$
\begin{bmatrix}  I_n & 0 \\ L_x & L_y \end{bmatrix}\begin{bmatrix} I_m \\ G'(\bf{a}) \end{bmatrix} = \begin{bmatrix} I_m & 0 \\ 0 & 0 \end{bmatrix}
$${#eq-thm-CM_implicit_function_theorem_5}

이며 이로부터 $L_x + L_y G'(\bf{a})=0$ 을 얻는다. $\square$

:::

</br><div class="border" style="background-color:#FFF0F5 ;padding:5px;">

::: {#thm-CM_implicit_function_theorem_2}

$F:\R^n \times \R^m  \to \R^m$ 가 $(\bf{a},\,\bf{b})\in \R^n \times \R^m$ 을 포함하는 열린 집합에서 $C^1$ 급 함수라고 하자. $F(\bf{a},\,\bf{b})=\bf{0}$ 이며 $\text{rank}(J_F(\bf{a},\,\bf{b})) = m$ 라면 $(\bf{a},\,\bf{b})$ 를 포함하는 어떤 열린 집합 $A\subset \R^{n+m}$ 에서 정의된, 아래의 ($1$), ($2$) 를 만족하는 $H: A\to \R^n \times \R^m$ 이 존재한다. 

&emsp;($1$) $H^{-1}$ 이 존재하고 미분가능하며,

&emsp;($2$) $(F\circ H)(\bf{x},\,\bf{y}) = \bf{y}$ 이다.

:::

</div>

::: {.proof}

우선 @thm-CM_implicit_function_theorem 와의 차이를 보자. 양쪽 모두 $F'(\bf{a},\,\bf{b})$ 는 $m \times (n +m )$ 행렬이다. @thm-CM_implicit_function_theorem 은 정체 행과 마지막 $m$ 개의 열로 이루어진 행렬의 행렬식이 $0$ 이 아난 경우, 즉 마지막 $m$ 개의 열이 선형독립인 경우이며, @thm-CM_implicit_function_theorem_2 는 전체 $m+n$ 개의 열 가운데 위치에 무관하게 $m$ 개의 열이 선형독립인 경우이다. 

이제 $m$ 개의 선형독립인 열의 인덱스를 $j_1,\ldots,\,j_m$ 이라고 하고 열에 대한 permutation $G: \R^n \times \R^m \to \R^n \times \R^m$ 을 $G(x_1,\ldots,\,x_{m+n}) = (\cdots, x_{j_1}, \ldots, x_{j_m})$ 이라고 하면 $F\circ G$ 는 @thm-CM_implicit_function_theorem 의 $F$ 와 똑같은 경우이다. 물론 $G$ 는 선형변환이며 따라서 전체 $\R^n \times \R^m$ 에서 $C^\infty$ 급 함수이다.

@thm-CM_implicit_function_theorem 에 따라 $F \circ G$ 에 대해

$$
(F \circ G)(\bf{x},\,K(\bf{x},\, \bf{y})) = \bf{y}
$$

인 미분가능한 함수 $K:\R^n \times \R^m \to \R^m$ 이 존재하며 $H=G \circ (\bf{x},\, K(\bf{x},\, \bf{y}))$ 라고 놓으면 된다. $\square$

:::

</br>

### 연습문제 {.unnumbered}


<div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_for_implicit_theorem_1}

$V\subset \R^{n}\times \R^{m}$ 이 열린 집합일 때 $W=\{\bf{x}\in \R^n : (\bf{x},\,\bf{0}) \in V\}$ 역시 열린집합임을 보여라.

:::

</div>

::: {.solution}

$V$ 가 열린집합이므로 $(\bf{x},\,\bf{0})\in V$ 일 때 $N((\bf{x},\,\bf{0}),\, \delta)\subset V$ 인 $\delta>0$ 이 존재한다. 그렇다면 $N(\bf{y},\,\delta)\subset W$ 이므로 $W$ 는 열린집합이다. 

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_40}
#### Spivak 2.40

음함수 정리를 이용하여 @exr-CM_spivak_2_15 ($c$) 를 다시 풀어라.

:::

</div>

::: {.solution}

@exr-CM_spivak_2_15 ($c$) 에서 $F = \R\times \R^n \to \R^n$ 을 $F=\begin{bmatrix}f_1 & \cdots f_n\end{bmatrix}^T$ 이며

$$
f_i (t,\,\bf{x}) = \sum_{j=1}^n a_{ij}(t)x_j - b_i(t)
$$

로 정의한다. $\det ([a_{ij}]) \ne 0$ 이므로 @thm-CM_implicit_function_theorem 에 의해 $F(t,\, X(t)) = 0$ 이 되도록 하는 미분가능한 $X(t) = \begin{bmatrix} x_1(t) & \cdots & x_n(t)\end{bmatrix}^T$ 가 존재한다.

:::

</br><div class="border" style="background-color:#F0FFFF  ;padding:5px;">

::: {#exr-CM_spivak_2_41}
#### Spivak 2.41

$f:\R \times \R \to \R$ 이 미분가능하다. 각각의 $x\in\R$ 에 대해 $g_x:\R \to \R$ 을 $g_x(y)= f(x,\,y)$ 로 정의하자. 각각의 $x$ 에 대해 $g_x'(y) = 0$ 이 되도록 하는 $y$ 가 유일하게 존재한다고 가정하고 이 $y$ 를 $c(x)$ 라고 하자.

($a$) 모든 $(x,\,y)$ 에 대해 $D_{2,2} f(x,\,y) \ne 0$ 이면 $c$ 는 미분가능하며

$$
c'(x) = - \dfrac{D_{2,1}f(x,\,c(x))}{D_{2,\,2}f(x,\,c(x))}
$$

임을 보여라.

($b$) $c'(x) =0$ 이면 어떤 $y$ 에서

$$
D_{2,1}f(x,\,y) = 0,\qquad D_2f(x,\,y) = 0
$$

임을 보여라.

($c$) $f(x,\,y) = x(y \ln y - y) - y \ln x$ 라고 하자. 다음을 구하라.

$$
\max_{\frac{1}{2} \le x \le 2} \left(\min_{\frac{1}{2} \le y \le 1} f(x,\,y)\right)
$$

:::

</div>

::: {.solution}

($a$) $g_x'(y) = 0$ 은 $D_{2}f(x,\,y)=0$ 과 같다는 것을 안다. $h(x,\,y)= D_2f(x,\,y)$ 라고 하자. $D_2 h = D_{2,2}f  \ne 0$ 이므로 $h(x,\, k(x)) = 0$ 을 만족하는 $y=k(x)$ 가 존재하며 이는 $c(x)$ 와 같다. 모든 $x\in \R$ 에 대해 $h(x,\,c(x))=0$ 이므로,

$$
0 = D_1 h(x,\,c(x)) = D_1h(x,\,c(x)) + c'(x) D_2h(x,\, c(x))
$$

이다. 따라서

$$
c'(x) = -\dfrac{D_1h(x,\,c(x))}{D_2 h(x,\,c(x))} = - \dfrac{D_{2, 1}h(x,\,c(x))}{D_{2,\,2} h(x,\,c(x))}
$$

이다.

($b$) ($a$) 로부터 $D_{2,1}f(x,\,c{x}) = 0$ 이므로 $y=c(x)$ 에서 $D_{2,1}f(x,\,y)=0$ 이다. $c(x)$ 의 정의에 의해 $D_2f(x,\,y) = g'(x,\,c(x))=0$ 이다.

($c$) 

:::

</br>

## 다변수 함수의 최대값과 최소값

열린 $E\subset \R^n \times \R^m$ 에서 정의된 $C^1$ 급 함수 $F: E \to \R^m$ 에 대해

$$
M_F := \{(\bf{x},\,\bf{y})\in E : F(\bf{x},\,\bf{y}) = \bf{0}\}
$$

를 생각하자. $\bf{p}=(\bf{a},\,\bf{b})\in M_F$ 이고 $\{ \nabla f^1(\bf{p}),\ldots,\, \nabla f^m(\bf{p})\}$ 가 선형 독립이면 $\R^m \times \R^m$ 의 좌표 순서를 적당히 바꿔서 $J_F(P)$ 의 마지막 $m\times m$ 행렬이 가역이 되도록 할 수 있다. 이제 $F$ 가 그러하다고 가정한다. 그랗다면 음함수 정리(@thm-CM_implicit_function_theorem) 를 적용 할 수 있다.

음함수 정리의 증명과정의 @eq-thm-CM_implicit_function_theorem_4 에서 $\Gamma (\bf{x})= H^{-1}(\bf{x},\,\bf{0})= (\bf{x},\,G(\bf{x}))$ 인 $C^1$ 급 함수 $\Gamma$ 를 생각 할 수 있다. $\Gamma$ 는 $W \to V \cap M_F$ 함수이며 $M_F$ 는 $m$ 차원 곡면임을 알 수 있다.

점 $P$ 를 지나고 $M_F$ 위에 있는 곡선

$$
X: (-\delta,\,\delta)  \to M_F,\qquad X(0) = \bf{p}
$$

을 생각 할 수 있다. $X$ 가 $t=0$ 에서 미분가능할 때 $X'(0)$ 을 $M_F$ 의 접벡터라고 한다. $F(X(t))=\bf{0}$ 이므로 $F'(X(0))X'(0)=\bf{0}$ 이며 따라서

$$
X'(0) \in \ker F'(\bf{p})
$$

이다. 역으로 $\bf{h}\in \R^n\times \R^m$ 이 $\bf{h}\in \ker F'(\bf{p})$ 라고 하자. $\bf{h}_1\in \R^n,\, \bf{h}_2\in \R^m$ 에 대해 $\bf{h} = (\bf{h}_1,\,\bf{h}_2)$ 라고 쓸 수 있다. $J_F(\bf{p}) = \begin{bmatrix}J_1 & J_2 \end{bmatrix}$ 에 대해

$$
J_F(\bf{p})\bf{h} = J_1\bf{h}_1 + J_2 \bf{h}_2 = \bf{0}
$$

이다. 이제 함수 $Y: (-\delta,\,\delta) \to M_F$ 를

$$
Y(t) := \Gamma (\bf{p}+ t\bf{h}_1)
$$

로 정의하자. 그렇다면

$$
Y'(0) = \begin{bmatrix} I_n \\ G'(\bf{a})\end{bmatrix}\bf{h}_1 = \begin{bmatrix} \bf{h}_1 \\ G'(\bf{a})\bf{h}_1\end{bmatrix} = \begin{bmatrix} \bf{h}_1 \\ -(J_2)^{-1}J_1 \bf{h}_1\end{bmatrix} = \begin{bmatrix} \bf{h}_1 \\ \bf{h}_2\end{bmatrix} = \bf{h}
$$

이므로 $\bf{h}$ 는 $\bf{p}$ 를 지나는 $M_F$ 의 접벡터이다. 즉 $\bf{p}$ 를 지나는 $M_F$ 의 접벡터의 집합은 $\ker F'(\bf{p})$ 와 일치한다. $\dim \ker F'(\bf{p}) = n$ 이므로 $M_F$ 의 접평먼도 $n$ 차원이다. $\{ \nabla f^1(\bf{p}),\ldots,\, \nabla f^m(\bf{p})\}$ 가 선형독립이며 이 접평면에 수직이므로 $\{ \nabla f^1(\bf{p}),\ldots,\, \nabla f^m(\bf{p})\}$ 가 $M_F$ 의 접평면에 수직인 공간의 기저임을 알 수 있다.